### ISSUE TITLE
Fatal error: Uncaught Error: Attempt to modify property "registered_blocks" on null in /wp-content/plugins/advanced-gutenberg-blocks/classes/Services/Blocks.php:51

### ISSUE THREAD

**Issue by sebastienserre** [maximebj/advanced-gutenberg-blocks#68]
Hello,

From today, I have a Fatal Error with WP-CLI running a `wp cron event run --due-now` (don't know there's a link between wp-cli command and the Fatale)

```
Fatal error: Uncaught Error: Attempt to modify property "registered_blocks" on null in /wp-content/plugins/advanced-gutenberg-blocks/classes/Services/Blocks.php:51
Stack trace:
#0 /wp-content/plugins/advanced-gutenberg-blocks/classes/Blocks/Plugin.php(28): AdvancedGutenbergBlocks\Services\Blocks::register_block()
#1 wp-content/plugins/advanced-gutenberg-blocks/classes/AdvancedGutenbergBlocks.php(99): AdvancedGutenbergBlocks\Blocks\Plugin->run()
#2/wp-content/plugins/advanced-gutenberg-blocks/plugin.php(22): AdvancedGutenbergBlocks\AdvancedGutenbergBlocks->run()
#3 /wp-settings.php(388): include_once('...')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#9 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#10 /usr/local/bin/wp(4): include('...')
#11 {main}
  thrown in /wp-content/plugins/advanced-gutenberg-blocks/classes/Services/Blocks.php on line 51
```
````
### wp-core ###

version: 5.6.1
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 5
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/thiverval-grignon
wordpress_size: 295,03 Mo (309360185 bytes)
uploads_path: /var/www/thiverval-grignon/wp-content/uploads
uploads_size: 2,32 Go (2489337749 bytes)
themes_path: /var/www/thiverval-grignon/wp-content/themes
themes_size: 5,24 Mo (5496186 bytes)
plugins_path: /var/www/thiverval-grignon/wp-content/plugins
plugins_size: 196,98 Mo (206543379 bytes)
database_size: 94,47 Mo (99059952 bytes)
total_size: 2,90 Go (3109797451 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Thiverval-Grignon V3 (thiverval-grignon_V3)
version: undefined
author: thivinfo.com
author_website: (undefined)
parent_theme: Twenty Fourteen (twentyfourteen)
theme_features: core-block-patterns, post-thumbnails, title-tag, editor-style, editor-styles, wp-block-styles, responsive-embeds, editor-color-palette, automatic-feed-links, menus, html5, post-formats, custom-background, featured-content, customize-selective-refresh-widgets, custom-header, widgets
theme_path: /var/www/thiverval-grignon/wp-content/themes/thiverval-grignon_V3
auto_update: Désactivé

### wp-parent-theme ###

name: Twenty Fourteen (twentyfourteen)
version: 3.0
author: L’équipe WordPress
author_website: https://wordpress.org/
theme_path: /var/www/thiverval-grignon/wp-content/themes/twentyfourteen
auto_update: Désactivé

### wp-themes-inactive (1) ###

Twenty Twenty-One: version: 1.1, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-mu-plugins (4) ###

Functions: version: 1.0.0, author: Sébastien SERRE
ManageWP - Worker Loader: author: GoDaddy, version: (undefined)
MU plugins subdirectory loader: version: 1.0, author: BeAPI, WeMakeCustom
tg-acf.php: author: (undefined), version: (undefined)

### wp-plugins-active (44) ###

AD Sliding FAQ: version: 2.4, author: Thomas Villain - Anybodesign, Mises à jour auto activées
Advanced Custom Fields: Autocomplete: version: 1.0.0, author: Brian S. Reed, Max Lyuchin, Mises à jour auto activées
Advanced Custom Fields: Extended: version: 0.8.7.6, author: ACF Extended, Mises à jour auto activées
Advanced Custom Fields PRO: version: 5.9.5, author: Elliot Condon, Mises à jour auto activées
Advanced Editor Tools (previously TinyMCE Advanced): version: 5.6.0, author: Automattic, Mises à jour auto activées
Advanced Gutenberg Blocks: version: 1.9.8, author: maximebj, Mises à jour auto activées
Akismet Anti-Spam: version: 4.1.8, author: Automattic, Mises à jour auto activées
Annuaire des prodessionels: version: 1.0.0, author: Sébastien SERRE, Mises à jour auto activées
Cantine: version: 1.0.0, author: Sébastien SERRE, Mises à jour auto activées
Classic Editor: version: 1.6, author: WordPress Contributors, Mises à jour auto activées
Comarquage service-public.fr: version: 0.5.58, author: Kienso, Mises à jour auto activées
Download Monitor: version: 4.4.4, author: Never5, Mises à jour auto activées
Easy FancyBox: version: 1.8.18, author: RavanH, Mises à jour auto activées
Gravity Forms: version: 2.4.22, author: Gravity Forms, Mises à jour auto activées
Gravity Forms + Custom Post Types: version: 3.1.16, author: spivurno, Mises à jour auto activées
Imagify: version: 1.9.14, author: WP Media, Mises à jour auto activées
iThemes Security: version: 7.9.0, author: iThemes, Mises à jour auto désactivées
MailPoet 3 (New): version: 3.59.2, author: MailPoet, Mises à jour auto activées
ManageWP - Worker: version: 4.9.8, author: GoDaddy, Mises à jour auto activées
Marché Public: version: 1.0.0, author: Sébastien SERRE, Mises à jour auto activées
MetaSlider: version: 3.20.2, author: MetaSlider, Mises à jour auto activées
MetaSlider Lightbox: version: 1.11.3, author: MetaSlider, Mises à jour auto activées
Post Expirator: version: 2.4.1, author: Aaron Axelsen, Mises à jour auto activées
Really Simple SSL: version: 4.0.8, author: Really Simple Plugins, Mises à jour auto activées
Redirection: version: 5.0.1, author: John Godley, Mises à jour auto activées
Redis Object Cache: version: 2.0.17, author: Till Krüss, Mises à jour auto activées
Registre: version: 1.0.0, author: Sébastien SERRE, Mises à jour auto activées
Relevanssi Premium: version: 2.3.0, author: Mikko Saari, Mises à jour auto activées
SEOPress: version: 4.4.0.3, author: SEOPress, Mises à jour auto activées
SEOPress PRO: version: 4.4.0, author: SEOPress, Mises à jour auto activées
SF Admin Bar Tools: version: 4.0, author: Grégory Viguier, Mises à jour auto activées
The Events Calendar: version: 5.3.2.1, author: The Events Calendar, Mises à jour auto activées
ThFO Custom: version: 1.0.0, author: Sébastien SERRE, Mises à jour auto activées
Travaux Communaux: author: Sébastien Serre, version: (undefined), Mises à jour auto activées
User Switching: version: 1.5.6, author: John Blackbourn & contributors, Mises à jour auto activées
Weather Station: version: 3.8.9, author: Pierre Lannoy, Mises à jour auto activées
WP-Matomo Integration: version: 1.0.24, author: André Bräkling, Mises à jour auto activées
WP-Optimize - Clean, Compress, Cache: version: 3.1.7, author: David Anderson, Ruhani Rabin, Team Updraft, Mises à jour auto activées
WP Crontrol: version: 1.9.1, author: John Blackbourn & crontributors, Mises à jour auto activées
WP Grid Builder: version: 1.5.3, author: Loïc Blascos, Mises à jour auto activées
WP Offload SES Lite: version: 1.4.4, author: Delicious Brains, Mises à jour auto désactivées
WP Rocket: version: 3.8.4, author: WP Media, Mises à jour auto désactivées
WP to Twitter: version: 3.5.0, author: Joseph C Dolson, Mises à jour auto activées
Yoast Duplicate Post: version: 4.1.1, author: Enrico Battocchi & Team Yoast, Mises à jour auto activées

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 50M
upload_max_filesize: 50M
max_effective_size: 50 Mo
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 Mo
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 Mo
	imagick::RESOURCETYPE_MEMORY: 256 Mo
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.9.0-9-amd64 x86_64
httpd_software: Apache
php_version: 7.3.27-2+0~20210213.78+debian9~1.gbpc9cf23 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 50M
php_post_max_size: 50M
curl_version: 7.52.1 OpenSSL/1.0.2u
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.1.48-MariaDB-0+deb9u1
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/thiverval-grignon/wp-content
WP_PLUGIN_DIR: /var/www/thiverval-grignon/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

```

**Comment by maximebj** [comment]
The plugin is not maintained anymore. I plan to write 1 plugin per block in the future if I can get time. But for now, I'm afraid I can't fix this error.
