### ISSUE TITLE
Fatal Error Occuring

### ISSUE THREAD

**Issue by DanielCryptoK** [maximebj/advanced-gutenberg-blocks#71]
Please see below message and advise

Uncaught Error: Attempt to modify property "registered_blocks" on null in /home/506952.cloudwaysapps.com/khytrmnsvp/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/Services/Blocks.php:51 Stack trace: #0 /home/506952.cloudwaysapps.com/khytrmnsvp/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/Blocks/Plugin.php(28): AdvancedGutenbergBlocks\Services\Blocks::register_block() #1 /home/506952.cloudwaysapps.com/khytrmnsvp/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/AdvancedGutenbergBlocks.php(99): AdvancedGutenbergBlocks\Blocks\Plugin->run() #2 /home/506952.cloudwaysapps.com/khytrmnsvp/public_html/wp-content/plugins/advanced-gutenberg-blocks/plugin.php(22): AdvancedGutenbergBlocks\AdvancedGutenbergBlocks->run() #3 /home/506952.cloudwaysapps.com/khytrmnsvp/public_html/wp-admin/includes/plugin.php(2300): include('/home/506952.cl...') #4 /home/506952.cloudwaysapps.com/khytrmnsvp/public_html/wp-admin/plugins.php(191): plugin_sandbox_scrape() #5 {main} thrown in /home/506952.cloudwaysapps.com/khytrmnsvp/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/Services/Blocks.php on line 51

**Comment by maximebj** [comment]
Since I wrote that plugin, Gutenberg has evolved many times, with a lot of breaking changes. They didn't provided retrocompatibility for this. 

Sadly, I don't have time anymore to maintain the project. I need to rewrite it from the floor but I currently have no time for this.

**Comment by DanielCryptoK** [comment]
over 1,000 pages I now need to update, happy days :)
